### ISSUE TITLE
Reordering UI

### ISSUE THREAD

**Issue by DivinoAG** [Sidem/sd-ui-plugins#2]
When reordering tokens with the current UI, you move one token at another token highlighted with the mouse cursor. It's not very clear to the user what happens when you drop it. If you drop the token close to the left side of the target's token it will be dropped before that target, and closer to the right it will drop after the target, but this isn't indicated in any way by the UI. By highlighting the entire target token it is also possible for the user to believe that the source and target tokens will switch places instead.

May I suggest that an icon that can be as simple as a single vertical line, usually hidden between each token, is displayed instead of highlighting the currently hovered token, indicating the exact place the new token will be placed?

The result would be as the following image:

![drag_token_ui](https://user-images.githubusercontent.com/5044664/199587750-1743bc36-82a3-4e2a-b4f7-7bbfa50d2cbe.png)

**Comment by Sidem** [comment]
Hi, currently the insertion always puts the dragged token behind the target token from the perspective of the dragged tokens origin. So if token A was located before token B and you drag A over B, A will insert after B.
If A is located after B and you drag A over B, A will be inserted before B.
Anyway I already considered a visualization like this and will work on an implementation when I have the time. Likely this weekend since I'm busy with my day job.

**Comment by Sidem** [comment]
Didn't mean to close it lol

**Comment by Sidem** [comment]
Implemented
